version: '3'

services:
    registrator:
      image: gliderlabs/registrator:latest
      container_name: registrator
      environment:
         USER_SERVER_NAME: "www.52db.club"
         RESTY_CONFIG_OPTIONS_MORE: "--with-echo_nginx_module"
      volumes:
         - /var/run/docker.sock:/tmp/docker.sock
      command: -ip="127.0.0.1" consul://localhost:8500 
      network_mode: host
      